# Generated by Django 4.1.4 on 2023-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='', upload_to='upload/about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
